name: Pipeline

on:
  schedule:
    - cron: '0 23 * * *' # Run every day at 11 PM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: uliba/news_twitter_bot:latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Environment Variables
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NEWS_API_ORG_API_KEY: ${{ secrets.NEWS_API_ORG_API_KEY }}
        run: |
          echo "BEARER_TOKEN=$BEARER_TOKEN" > .env
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> .env
          echo "ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET" >> .env
          echo "CONSUMER_KEY=$CONSUMER_KEY" >> .env
          echo "CONSUMER_SECRET=$CONSUMER_SECRET" >> .env
          echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> .env
          echo "NEWS_API_ORG_API_KEY=$NEWS_API_ORG_API_KEY" >> .env
          cat .env

      - name: Run python script
        run: |
          python3 tweet.py